# Generated by Django 4.1.1 on 2022-10-13 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_image', models.ImageField(upload_to='Oimages/')),
                ('thumbnail_image', models.ImageField(upload_to='Cimages/')),
                ('medium_image', models.ImageField(upload_to='Cimages/')),
                ('large_image', models.ImageField(upload_to='Cimages/')),
                ('grayscale_image', models.ImageField(upload_to='Cimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user')),
            ],
        ),
    ]
