# Generated by Django 4.1.1 on 2022-10-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user'),
        ),
    ]
