# Generated by Django 4.1.1 on 2022-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_alter_uploads_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='grayscale_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='large_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='medium_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
